discourse/discourse-docs

- assets/javascripts/discourse/controllers/knowledge-explorer.js.es6
- assets/javascripts/discourse/models/knowledge-explorer.js.es6
- lib/knowledge_explorer/query.rb
We were loading every topic into memory, so for large datasets this blew up. 
@davidtaylorhq already ran through a review on this and gave the go-ahead so I'm going to merge.
> PERF: Use DB for topic enumeration tasks

- Gemfile
- Gemfile.lock
- app/controllers/knowledge_explorer/knowledge_explorer_controller.rb
- app/views/knowledge_explorer/knowledge_explorer/get_topic.html.erb
- assets/javascripts/discourse/controllers/knowledge-explorer.js.es6
- assets/javascripts/discourse/models/knowledge-explorer.js.es6
- spec/requests/knowledge_explorer_controller_spec.rb
Currently linking directly to Knowledge Explorer topics shows a generic onebox, which isn't super helpful in some cases. 
This commit mimics how the theme creator plugin handles adding metadata to special occurrences. However, to get this to work, how the plugin handles showing topic contents needed to be refactored. Instead of hitting the existing topic route, the plugin implements its own version of this, including adding restrictions for topics that are not in a selected Knowledge Explorer category or tag.
I've verified the correct metadata shows up when visiting the page, but locally this was not rendering when pasting a link to a post. It may need some more testing, but the logic appears to be correct.
> REFACTOR/FEATURE: Add onebox metadata

- app/controllers/knowledge_explorer/knowledge_explorer_controller.rb
- spec/requests/knowledge_explorer_controller_spec.rb
There was a bug with the logic in how we were checking for matching tags and categories in KE settings. If only tags were set, topics would not show.
Also added some tests to check this in the future.
> FIX: Topics not always properly shown

- lib/knowledge_explorer/query.rb
- spec/requests/knowledge_explorer_controller_spec.rb
https://meta.discourse.org/t/error-when-adding-3-or-4-filters-to-knowledge-explorer-plugin/167123/
If using more than two tags to filter, we'd run into an SQL alias
collision on a few joins. Resolved by ensuring unique names are used across the query.
> FIX: Query name collision with multiple filters

- assets/javascripts/discourse/components/knowledge-explorer-category.js.es6
- assets/javascripts/discourse/components/knowledge-explorer-search.js.es6
- assets/javascripts/discourse/components/knowledge-explorer-tag.js.es6
- assets/javascripts/discourse/components/knowledge-explorer-topic-list.js.es6
- assets/javascripts/discourse/components/knowledge-explorer-topic.js.es6
- assets/javascripts/discourse/controllers/knowledge-explorer.js.es6
- assets/javascripts/discourse/models/knowledge-explorer.js.es6
- assets/javascripts/discourse/routes/knowledge-explorer.js.es6
This had been hanging in the black hole of my todo list for a while -- needed to fix the deprecated methods of creating Ember classes and objects. This PR handles that job.
> DEV: Fix deprecated object creation methods

- lib/knowledge_explorer/query.rb
- spec/requests/knowledge_explorer_controller_spec.rb
After implementing changes to tagging, this introduced ambiguity in the SQL query for sorting by activity. This commit fixes the ambiguity by explicitly defining the table from where the columns are used. Also adds tests to check for regressions in the future.
> FIX: Sort query was ambiguous

- spec/requests/knowledge_explorer_controller_spec.rb
In Spec we were creating two topics:
```ruby
fab!(:topic) { Fabricate(:topic, category: category) }
fab!(:topic2) { Fabricate(:topic, category: category) }
```
Because we didn't set title explicitly it was using sequence from Fabricator
```ruby
title { sequence(:title) { |i| "This is a test topic #{i}" } }
```
If you have two titles `This is a test topic 9` and `This is a test topic 10` Spec testing if topics are sorted will fail. 
Therefore, we should explicitly set topic title when creating test instances to avoid that randomness.
> FIX: flaky order in spec

- assets/javascripts/discourse/controllers/knowledge-explorer-index.js.es6
- assets/javascripts/discourse/routes/knowledge-explorer-index.js.es6
Pre-loading/pre-assigning isn't necessary. `Topic.category` uses `Category.findById` which in turn uses an identity map, so there are no N+1 calls to the backend.
> FIX: Don't overwrite Topic.category computed prop

- lib/knowledge_explorer/query.rb
- plugin.rb
In many cases it makes sense to show muted topics in the Knowledge Explorer view. One such case might be if a user mutes a documentation category, but wants to be able to search them via this plugin. 
To implement this, I've called `TopicQuery.default_results` via an added class method, which does the same thing as `latest_results` except skips the muted topics removal.
One issue I ran into with this is with the `no_definitions` option set to `true`, the query was not able to see the `categories` table. This appears to work correctly in core as I dug into it, but was not able to root out the source of the issue in the plugin. Everything seems to be generated correctly compared to how core methods use `TopicQuery`, but this issue remained. This is the reason for the …
> FIX: Show muted topics

- assets/javascripts/discourse/controllers/knowledge-explorer-index.js.es6
- assets/javascripts/discourse/controllers/knowledge-explorer.js.es6
- assets/javascripts/discourse/templates/knowledge-explorer-index.hbs
- lib/knowledge_explorer/query.rb
- spec/requests/knowledge_explorer_controller_spec.rb
There was a weird case where when filtering topics by solved status did not properly show the count of filtered topics. I took this opportunity to lightly refactor the backend. There was a duplicate size operation when we searched and when calculating pagination. I've eliminated the second size call and refactored the front end to be a little bit simpler while solving the bug.
Also tried to create a 2nd PR from another branch for the import transition commit below but somehow that wasn't done correctly. Sorry about that.
> FIX: Results count not always properly shown

- assets/javascripts/discourse/components/knowledge-explorer-search.js.es6
We recently merged a Discourse core's PR to replace usages of Ember's debounce and discourseDebounce with a new debounce wrapper. The new wrapper works exactly like Ember's debounce but internally calls "run" when called in test mode.
This PR replaces all usages of other debounce functions with the new wrapper and fallbacks to Ember's debounce for backward-compatibility.
> DEV: Use the new discourseDebounce function wrapper.

- assets/javascripts/discourse/components/knowledge-explorer-search.js.es6
`debounce` doesn't work correctly if it's given a new instance of the callback function each time it's called. The knowledge explorer search bar is currently broken because of that.
Signed-off-by: OsamaSayegh <asooomaasoooma90@gmail.com>
> FIX: debounce search correctly

- assets/javascripts/discourse/templates/components/knowledge-explorer-topic.hbs
Topic titles with unicode elements were displaying uncooked.
> FIX: Show unicode title in topic view

- assets/javascripts/discourse/components/docs-topic.js.es6
- assets/javascripts/discourse/templates/components/docs-topic.hbs
Was using `unicode_title` but not all topics return a unicode_title
attribute. So need to instead do this.
> FIX: Compute topic title correctly

- assets/stylesheets/common/docs.scss
Core made buttons to use flexbox recently, which changed the behavior of
the go back button on Docs topics. The local justify-content declaration
overrides the core declaration causing problems.
> FIX: Back button out of alignment

- app/controllers/docs/docs_controller.rb
- app/views/docs/docs/get_topic.html.erb
Linking directly to a Docs item like so `http://localhost:3000/docs?topic=16` would result in a generic inline onebox link. This adds logic to the Rails view so a proper title is rendered when the `InlineOneboxer` in core queries the route.
> FEATURE: Make Docs compatible with inline oneboxes

- assets/javascripts/discourse/initializers/setup-docs.js.es6
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/settings.yml
Simple PR, feature request here: https://meta.discourse.org/t/docs-add-link-to-top-menu/177340
Added a plugin setting so admins have the choice of including a link to Docs in the top menu.
> FEATURE: Add link to Docs in top menu

- assets/stylesheets/common/docs.scss
- assets/stylesheets/mobile/docs.scss
- adds bottom padding on mobile to avoid items staying hidden below the footer nav in DiscourseHub
- break words in titles so the list doesn't expand the width of the container due to a long space-less title (esp on mobile)
> UX: Fix two small mobile styling issues

- assets/javascripts/discourse/templates/docs.hbs
This adds a parameters to the args hash of the `before-docs-search` plugin outlet so we can access tags via theme components using this outlet.
> DEV: Add parameter to plugin outlet

- lib/docs/query.rb
Related to https://github.com/discourse/discourse/pull/12688.
The tags and categories count queries are failing on Rails 6.1 with `ERROR:  column "topics.bumped_at" must appear in the GROUP BY clause or be used in an aggregate function`. The reason these queries didn't fail prior to 6.1 was because Active Record would automatically drop the `ORDER BY` clause from the queries when we called `count` on them. This behavior has been [changed](https://github.com/rails/rails/commit/5812feffe321f18e244f212abfe884ad83215554) in 6.1 so now Active Record only drops the `ORDER BY` clause if there is no `GROUP BY` clause. Our queries do have `GROUP BY` clauses, so we need to drop the `ORDER BY` clauses ourselves before we call `count` to make them work on 6.1.
> DEV: Compatibility with Discourse on Rails 6.1

- lib/docs/query.rb
- spec/requests/docs_controller_spec.rb
Category filter accepts ids of categories. If value is manipulated, we should ignore it.
> FIX: ignore category filter when incorrect param

- assets/stylesheets/common/docs.scss
- assets/stylesheets/mobile/docs.scss
> UX: Solved filter alignment adjustment

- assets/javascripts/discourse/templates/components/docs-topic.hbs
- assets/javascripts/discourse/templates/docs-index.hbs
- assets/javascripts/discourse/templates/docs.hbs
Core's defaults are changing in https://github.com/discourse/discourse/pull/13685. This commit ensures the behaviour of this plugin will not change.
> DEV: Update plugin-outlet arguments

- assets/javascripts/discourse/components/docs-topic.js.es6
- assets/javascripts/discourse/templates/docs-index.hbs
- adds a new `below-docs-topic` outlet
- emits a `docs-topic:current-post-scrolled` event that can be consumed by other plugins (DiscoTOC will use this to calculate the scroll position of the active heading)
- fixes an unrelated bug that would result in `TypeError: undefined is not an object (evaluating 'this.topic.post_stream.posts')` console errors
> DEV: Add outlet + scroll event to support DiscoTOC

- app/controllers/docs/docs_controller.rb
- assets/javascripts/discourse/models/docs.js.es6
- spec/requests/docs_controller_spec.rb
When a documentation topic is viewed, corresponding TopicViewItem and TopicUser should be created.
A method from a TopicController is called to avoid duplication. Added specs should warn us if ever that core method would change.
> FIX: TopicViewItem and TopicUser for doc topics

- assets/javascripts/discourse/templates/docs-index.hbs
This plugin outlet will allow developers to insert a HTML element so they can create a custom checkbox using a sibling selector (before/after psudos do not work directly on inputs). 
(using this for a customer theme)
> DEV: add plugin outlet to enable custom checkbox css

- assets/javascripts/discourse/components/docs-topic-list.js
- assets/javascripts/discourse/controllers/docs-index.js
- assets/javascripts/discourse/templates/docs-index.hbs
- assets/javascripts/discourse/templates/docs-topic-link.hbr
We can rip out the `click` handler completely and just lean on the _logic_ we have in `docs-index`. 
https://github.com/discourse/discourse-docs/blob/0cef82aec0abcf500affa80e16b8696dfee708e0/assets/javascripts/discourse/routes/docs-index.js#L12
It will always refresh the `selectedTopic` so there will be no need to update it within the click handler. Which then nullifies the need for `setSelectedTopic`.
> DEV: update routing to allow for open_in_new_tab

- assets/javascripts/discourse/controllers/docs-index.js
Context: https://deprecations.emberjs.com/v3.x/#toc_ember-string-prototype_extensions
> DEV: Remove 'htmlSafe' string prototype extensions

- test/javascripts/acceptance/docs-test.js
CSS can slightly affect the result of element.innerText. Preparation for https://github.com/discourse/discourse/pull/18668
> DEV: Ensure tests work when plugin CSS is loaded

- assets/javascripts/discourse/controllers/docs-index.js
- assets/javascripts/discourse/templates/components/docs-category.hbs
- assets/stylesheets/common/docs.scss
- lib/docs/query.rb
- plugin.rb
- spec/requests/docs_controller_spec.rb
> UX: Expand category filters even when already filtered

- test/javascripts/acceptance/docs-test.js
This PR https://github.com/discourse/discourse/pull/19406 enables the
sidebar on by default, so we need to set the sidebar to legacy like the
original test assumed.
> DEV: Fix failing test if sidebar is enabled by default

- assets/javascripts/discourse/controllers/docs-index.js
- test/javascripts/unit/controllers/docs-index-test.js
In some cases, when having multiple tag filters selected and results in the list, deselecting one of the filters would cause no results. This is clearly incorrect behavior, as fewer filters should lead to more (or at least the same number of) results.
This happens when you have a list of selected filters, e.g. `foo|bar|baz`, and you deselect the "middle" one. This will result in the following filter: `foo||baz`, which causes the back-end to try and filter on empty string as well, and in turn leads to no results.
The order of the filter list depends on the order they were selected, which caused this to seem a bit erratic.
In the code, there's a regular expression that tries to remove consecutive `|` characters, but this is anchored to the beginning of the string, so it doesn't work for …
> FIX: Fix an issue where deselecting a tag filter would cause no results

- assets/stylesheets/common/docs.scss
This button doesn't work in the docs topic view. The docs plugin has deliberately disabled other forms of interactivity on posts (e.g. reply/edit/quote), so it makes sense to hide this as well.
https://meta.discourse.org/t/discourse-docs-topics-edit-history-modal-does-not-open-on-click/260285/4?u=david
> UX: Hide non-functional revision history button

- assets/javascripts/discourse/templates/docs-index.hbs
**This PR fixes a regression causing the icons in the sidebar to not render.**
---
**Before:**
**After:**
> FIX: Icons not appearing

- app/controllers/docs/docs_controller.rb
- plugin.rb
This resulted in `Required plugin 'docs' not found` warnings in logs
> FIX: Incorrect plugin name in `requires_plugin`

- app/controllers/docs/docs_controller.rb
- lib/docs/engine.rb
- lib/onebox/templates/discourse_docs_list.mustache
- plugin.rb
- spec/plugin_spec.rb
Docs (`/docs`) links to the same Discourse instance weren't supported because there were no local Onebox handlers for these Docs URLs.
This PR adds local Oneboxer and InlineOneboxer handlers to support the Docs lists (any `/docs` URL without a `topic` query param) and Docs topics (`/docs?topic=N`).
Docs lists are rendered as a generic Onebox with a `js.docs.title` title.
A Docs topic is rendered exactly like a non-Doc topic, with the OP avatar, category boxes, and excerpt, and it's also expandable.
> FEATURE: add local onebox handler for /docs urls

- test/javascripts/acceptance/docs-user-status-test.js
Why this change?
In Discourse core, we have made the change to raise an error when a
interpolation argument is missing when calling `I18n.translate` to help
catch regressions in the UI where we may end up displaying broken
translations.
> DEV: Correct fixtures to avoid translations error

- test/javascripts/acceptance/docs-test.js
Why this change?
The legacy navigation menu has been deprecated for quite awhile and will
soon be removed.
What does this change do?
Update the tests to test against the `sidebar` navigation menu instead
which is the default for a new Discourse install.
> DEV: Update QUnit acceptance tests to not rely on legacy nav menu

- assets/javascripts/discourse/initializers/setup-docs.js
The `legacy` option has been removed from the `navigation_menu` site setting, so we can remove all the logic that's related to the `legacy` option from this plugin.
Internal topic: t/113137.
> DEV: Remove decoration for legacy hamburger menu

- assets/javascripts/discourse/models/docs.js
- lib/docs/query.rb
- spec/requests/docs_controller_spec.rb
Not all categories are preloaded when lazy_load_categories is enabled. In this case, the category objects that are loaded through /docs.json must be complete.
> FIX: Load complete category objects

- app/controllers/docs/docs_controller.rb
When https://github.com/discourse/discourse/pull/27761 is
merged in core the v2 method name is obsolete and we
can call `defer_track_visit` once more.
> DEV: Update defer_track_visit method in line with core

- app/controllers/docs/docs_controller.rb
- spec/requests/docs_controller_spec.rb
We're expecting the `tags` parameter to be a string. But the client can send an array or a nested parameter (thanks to the Rack protocol.) We're seeing exceptions in logs where the application is erroring out because of this.
Raise a `Discourse::InvalidParameters` exception if we get a non-stringy `tags` parameter.
> FIX: Don't error out on non-stringy tags parameter

- assets/javascripts/discourse/components/docs-category.hbs
This PR updates the deprecated `times-circle` icon name. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
> DEV: update deprecated icon names times-circle

- assets/javascripts/discourse/components/docs-topic.js
This is necessary due to upcoming changes in the post model for the Glimmer post stream.
The post widgets expect to receive a transformed post as argument and use the spread operator to pass attributes to the inner widget, however the Docs plugin was providing a post model instance as argument instead.
This used to work fine, but as we introduce tracked properties in the post model, the spread operator doesn't copy their values, which causes issues.
This PR changes the DocsTopic Component to provide a transformedPost as argument to the post widget instead.
> DEV: Use `transformedPost` as args to the Post widget

- spec/system/docs_index_spec.rb
With core themes, the first theme does not have to be the default one.
Correlated draft PR with core themes: https://github.com/discourse/discourse/pull/32681
> DEV: docs index spec working with core themes
